## Promise.all()

`Promise.all()` 方法接收一个 `promise` 的 `iterable` 类型（注：`Array，Map，Set` 都属于 ES6 的 `iterable` 类型）的输入，并且只返回一个`Promise`实例， 那个输入的所有 `promise` 的 `resolve` 回调的结果是一个数组。这个`Promise`的 `resolve` 回调执行是在所有输入的 `promise` 的 `resolve` 回调都结束，或者输入的 `iterable` 里没有 `promise` 了的时候。它的 `reject` 回调执行是，只要任何一个输入的 `promise` 的 `reject` 回调执行或者输入不合法的 `promise` 就会立即抛出错误，并且 `reject` 的是第一个抛出的错误信息。

这样的话，我们就可以做一个简单地总结：

- `Promise.all()`方法就是检测参数数组内部的所有 Promise 实例是否成功，若成功，则调用 then 方法进行处理，否则变为 reject 状态。

```js
function fn(time, isResolve) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      isResolve
        ? resolve(`${time}毫秒后我成功啦！！！`)
        : reject(`${time}毫秒后我失败啦！！！`);
    }, time);
  });
}

Promise.all([
  fn(3000, true), 
  fn(1000, true), 
  fn(1000, true), 
  fn(2000, true)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// [
//     "3000毫秒后我成功啦！！！",
//     "1000毫秒后我成功啦！！！",
//     "1000毫秒后我成功啦！！！",
//     "2000毫秒后我成功啦！！！"
// ]

Promise.all([
  fn(3000, true), 
  fn(1000, false), 
  fn(1000, true), 
  fn(2000, false)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// 1000毫秒后我失败啦！！！
```

## Promise.race()

`Promise.race(iterable)` 方法返回一个 `promise`，一旦迭代器中的某个 `promise` 解决或拒绝，返回的 `promise` 就会解决或拒绝。
- `race`是竞赛赛跑的意思，竞赛肯定最受关注的就是第一名，其他的就无所谓了。

```js
function fn(time, isResolve) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      isResolve
        ? resolve(`${time}毫秒后我成功啦！！！`)
        : reject(`${time}毫秒后我失败啦！！！`);
    }, time);
  });
}

Promise.race([
  fn(3000, true), 
  fn(1000, true), 
  fn(1000, true), 
  fn(2000, true)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// 1000毫秒后我成功啦！！！

Promise.race([
  fn(3000, true), 
  fn(1000, false), 
  fn(1000, true), 
  fn(2000, false)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// 1000毫秒后我失败啦！！！
```

## Promise.allSettled()

该`Promise.allSettled()`方法返回一个在所有给定的 `promise` 都已经`fulfilled`或`rejected`后的 `promise`，并带有一个对象数组，每个对象表示对应的 `promise` 结果。

- 当您有多个彼此不依赖的异步任务成功完成时，或者您总是想知道每个`promise`的结果时，通常使用它。

- 相比之下，`Promise.all()` 更适合彼此相互依赖或者在其中任何一个`reject`时立即结束。

```js
function fn(time, isResolve) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      isResolve
        ? resolve(`${time}毫秒后我成功啦！！！`)
        : reject(`${time}毫秒后我失败啦！！！`);
    }, time);
  });
}

Promise.allSettled([
  fn(3000, true), 
  fn(1000, true), 
  fn(1000, true), 
  fn(2000, true)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// [
//     {
//         "status": "fulfilled",
//         "value": "3000毫秒后我成功啦！！！"
//     },
//     {
//         "status": "fulfilled",
//         "value": "1000毫秒后我成功啦！！！"
//     },
//     {
//         "status": "fulfilled",
//         "value": "1000毫秒后我成功啦！！！"
//     },
//     {
//         "status": "fulfilled",
//         "value": "2000毫秒后我成功啦！！！"
//     }
// ]

Promise.allSettled([
  fn(3000, true), 
  fn(1000, false), 
  fn(1000, true), 
  fn(2000, false)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// [
//     {
//         "status": "fulfilled",
//         "value": "3000毫秒后我成功啦！！！"
//     },
//     {
//         "status": "rejected",
//         "reason": "1000毫秒后我失败啦！！！"
//     },
//     {
//         "status": "fulfilled",
//         "value": "1000毫秒后我成功啦！！！"
//     },
//     {
//         "status": "rejected",
//         "reason": "2000毫秒后我失败啦！！！"
//     }
// ]
```

## Promise.any()

`Promise.any()` 接收一个`Promise`可迭代对象，只要其中的一个 `promise` 成功，就返回那个已经成功的 `promise` 。如果可迭代对象中没有一个 `promise` 成功（即所有的 `promises` 都失败/拒绝），就返回一个失败的 `promise` 和`AggregateError`类型的实例，它是 `Error` 的一个子类，用于把单一的错误集合在一起。本质上，这个方法和 `Promise.all()` 是相反的。


```js
function fn(time, isResolve) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      isResolve
        ? resolve(`${time}毫秒后我成功啦！！！`)
        : reject(`${time}毫秒后我失败啦！！！`);
    }, time);
  });
}

Promise.any([
  fn(3000, true), 
  fn(1000, true), 
  fn(1000, true), 
  fn(2000, true)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// 1000毫秒后我成功啦！！！

Promise.any([
  fn(3000, true), 
  fn(1000, false), 
  fn(1000, true), 
  fn(2000, false)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// 1000毫秒后我成功啦！！！

Promise.any([
  fn(3000, false), 
  fn(1000, false), 
  fn(1000, false), 
  fn(2000, false)
])
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
// 结果
// AggregateError: All promises were rejected
```

## 总结

相同点这四种方法的参数都是包含Promise实例的数组。

看下不同点：

**作用**：

-   `Promise.all()` 全成功我成功 失败一个我失败
-   `Promise.race()` 谁第一个改变状态就是谁的，无论成功或失败
-   `Promise.allSettled()` 管你成功或失败，全部都得运行完
-   `Promise.any()` 一个成功我成功，全部失败我失败

**状态成功时返回值：**

-   `Promise.all()` 返回状态成功时的数组
-   `Promise.race()` 第一个成功的
-   `Promise.allSettled()` 无所谓成功或失败，返回值都是一个包含状态对象的数组
-   `Promise.any()` 返回第一个成功的

**状态失败时返回值：**

-   `Promise.all()` 第一个失败的
-   `Promise.race()` 第一个失败的
-   `Promise.allSettled()` 无所谓成功或失败，返回值都是一个包含状态对象的数组
-   `Promise.any()` AggregateError: All promises were rejected

**是否将参数数组内部的Promise实例全部执行完，才调用**

-   `Promise.all()` 成功是，失败否
-   `Promise.race()` 不是
-   `Promise.allSettled()` 是
-   `Promise.any()` 成功否，失败是
